### ISSUE TITLE
V1.0 Checklist

### ISSUE THREAD

**Issue by WilliamHayward** [WilliamHayward/Lipwig-Client#1]
Before V1.0 is released, here's the goals:

# Essential
- [ ] Unit Testing
- [ ] Device reconnection handling
- [ ] Investigate Garbage Collection and performance
- [ ] Message validation
- [ ] Message filtering
- [ ] Group assignment
- [ ] API Documentation
- [ ] Refactor public/private for variables, methods, and classes

# Optional
- [ ] Wild Card Events
- [ ] Ask/response system
- [ ] General code refactor

**Comment by WilliamHayward** [comment]
API is going well! Check the wiki for progress so far - all but 3 classes documented.

Going through the methods has made me realise that 

 a) Most of the public/private variables and methods are already fine

 b) Since the transpiled JavaScript doesn't have a concept of public/private, it's less important than originally expected. Gonna tick that one off.

**Comment by WilliamHayward** [comment]
Is message validation suuuuper needed for clientside? The server will have it, and so the just needs to

a) Trust that any messages received from the server are valid

and

b) Construct valid messages.

It's gonna be needed somewhere down the line to verify b, but 1.0 is more about getting the base implemenation up and ironclad

**Comment by WilliamHayward** [comment]
It's probably going to use very similar code to the serverside verification, but I'm moving message validation to optional
